version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rick-and-morty-demo
    restart: always
    ports:
      - "8003;8003"
    networks:
      - vps-internal
    environment:
      - NODE_ENV=production
      # Add other environment variables as needed

networks:
  default:
    external: true
    name: vps-internal
